version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
      build: ./back-end
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=mysql://root:123456@mysql:3306/bookstore
      depends_on:
        mysql:
          condition: service_healthy
  frontend:
      build: ./front-end
      ports:
        - "8080:80"
      environment:
        - VITE_API_URL=http://127.0.0.1:5000
      depends_on:
        - backend
volumes:
  mysql_data:
